version: "2"

volumes:
  apps:
  config:
  data:
  mariadb:

services:
  app:
    build: .
    volumes:
    - apps:/var/www/html/apps
    - config:/var/www/html/config
    - data:/var/www/html/data
    depends_on:
    - mariadb
    ports:
    - 8000:80

  mariadb:
    image: mariadb
    volumes:
    - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: secret
